//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.23 at 03:05:02 PM MUT 
//


package com.bornfire.jaxb.pain_001_001_09;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bornfire.jaxb.pain_001_001_09 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:pain.001.001.09", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bornfire.jaxb.pain_001_001_09
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice1 }
     * 
     */
    public AccountIdentification4Choice1 createAccountIdentification4Choice1() {
        return new AccountIdentification4Choice1();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link AmountType4Choice1 }
     * 
     */
    public AmountType4Choice1 createAmountType4Choice1() {
        return new AmountType4Choice1();
    }

    /**
     * Create an instance of {@link Authorisation1Choice1 }
     * 
     */
    public Authorisation1Choice1 createAuthorisation1Choice1() {
        return new Authorisation1Choice1();
    }
    
    
    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification61 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification61 createBranchAndFinancialInstitutionIdentification61() {
        return new BranchAndFinancialInstitutionIdentification61();
    }

    /**
     * Create an instance of {@link CashAccount381 }
     * 
     */
    public CashAccount381 createCashAccount381() {
        return new CashAccount381();
    }

    /**
     * Create an instance of {@link CashAccountType2Choice }
     * 
     */
    public CashAccountType2Choice createCashAccountType2Choice() {
        return new CashAccountType2Choice();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice1 }
     * 
     */
    public CategoryPurpose1Choice1 createCategoryPurpose1Choice1() {
        return new CategoryPurpose1Choice1();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification21 }
     * 
     */
    public ClearingSystemMemberIdentification21 createClearingSystemMemberIdentification21() {
        return new ClearingSystemMemberIdentification21();
    }

    /**
     * Create an instance of {@link CreditTransferTransaction341 }
     * 
     */
    public CreditTransferTransaction341 createCreditTransferTransaction341() {
        return new CreditTransferTransaction341();
    }

    /**
     * Create an instance of {@link CustomerCreditTransferInitiationV09 }
     * 
     */
    public CustomerCreditTransferInitiationV09 createCustomerCreditTransferInitiationV09() {
        return new CustomerCreditTransferInitiationV09();
    }

    /**
     * Create an instance of {@link DateAndDateTime2Choice1 }
     * 
     */
    public DateAndDateTime2Choice1 createDateAndDateTime2Choice1() {
        return new DateAndDateTime2Choice1();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification181 }
     * 
     */
    public FinancialInstitutionIdentification181 createFinancialInstitutionIdentification181() {
        return new FinancialInstitutionIdentification181();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification11 }
     * 
     */
    public GenericAccountIdentification11 createGenericAccountIdentification11() {
        return new GenericAccountIdentification11();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification11 }
     * 
     */
    public GenericFinancialIdentification11 createGenericFinancialIdentification11() {
        return new GenericFinancialIdentification11();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification11 }
     * 
     */
    public GenericOrganisationIdentification11 createGenericOrganisationIdentification11() {
        return new GenericOrganisationIdentification11();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification11 }
     * 
     */
    public GenericPersonIdentification11 createGenericPersonIdentification11() {
        return new GenericPersonIdentification11();
    }

    /**
     * Create an instance of {@link GroupHeader851 }
     * 
     */
    public GroupHeader851 createGroupHeader851() {
        return new GroupHeader851();
    }

    /**
     * Create an instance of {@link InstructionForCreditorAgent11 }
     * 
     */
    public InstructionForCreditorAgent11 createInstructionForCreditorAgent11() {
        return new InstructionForCreditorAgent11();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice1 }
     * 
     */
    public LocalInstrument2Choice1 createLocalInstrument2Choice1() {
        return new LocalInstrument2Choice1();
    }

    /**
     * Create an instance of {@link OrganisationIdentification291 }
     * 
     */
    public OrganisationIdentification291 createOrganisationIdentification291() {
        return new OrganisationIdentification291();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link Party38Choice1 }
     * 
     */
    public Party38Choice1 createParty38Choice1() {
        return new Party38Choice1();
    }

    /**
     * Create an instance of {@link PartyIdentification1351 }
     * 
     */
    public PartyIdentification1351 createPartyIdentification1351() {
        return new PartyIdentification1351();
    }

    /**
     * Create an instance of {@link PaymentIdentification61 }
     * 
     */
    public PaymentIdentification61 createPaymentIdentification61() {
        return new PaymentIdentification61();
    }

    /**
     * Create an instance of {@link PaymentInstruction301 }
     * 
     */
    public PaymentInstruction301 createPaymentInstruction301() {
        return new PaymentInstruction301();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation261 }
     * 
     */
    public PaymentTypeInformation261 createPaymentTypeInformation261() {
        return new PaymentTypeInformation261();
    }

    /**
     * Create an instance of {@link PersonIdentification131 }
     * 
     */
    public PersonIdentification131 createPersonIdentification131() {
        return new PersonIdentification131();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link PostalAddress241 }
     * 
     */
    public PostalAddress241 createPostalAddress241() {
        return new PostalAddress241();
    }

    /**
     * Create an instance of {@link ProxyAccountIdentification1 }
     * 
     */
    public ProxyAccountIdentification1 createProxyAccountIdentification1() {
        return new ProxyAccountIdentification1();
    }

    /**
     * Create an instance of {@link ProxyAccountType1Choice }
     * 
     */
    public ProxyAccountType1Choice createProxyAccountType1Choice() {
        return new ProxyAccountType1Choice();
    }

    /**
     * Create an instance of {@link Purpose2Choice }
     * 
     */
    public Purpose2Choice createPurpose2Choice() {
        return new Purpose2Choice();
    }

    /**
     * Create an instance of {@link RegulatoryReporting31 }
     * 
     */
    public RegulatoryReporting31 createRegulatoryReporting31() {
        return new RegulatoryReporting31();
    }

    /**
     * Create an instance of {@link RemittanceInformation161 }
     * 
     */
    public RemittanceInformation161 createRemittanceInformation161() {
        return new RemittanceInformation161();
    }

    /**
     * Create an instance of {@link ServiceLevel8Choice1 }
     * 
     */
    public ServiceLevel8Choice1 createServiceLevel8Choice1() {
        return new ServiceLevel8Choice1();
    }

    /**
     * Create an instance of {@link StructuredRegulatoryReporting31 }
     * 
     */
    public StructuredRegulatoryReporting31 createStructuredRegulatoryReporting31() {
        return new StructuredRegulatoryReporting31();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    
    
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:pain.001.001.09", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
