//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.04 at 04:52:11 PM IST 
//


package com.bornfire.jaxb.pacs_002_001_010;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bornfire.jaxb.pacs_002_001_010 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:pacs.002.001.10", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bornfire.jaxb.pacs_002_001_010
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice1 }
     * 
     */
    public AccountIdentification4Choice1 createAccountIdentification4Choice1() {
        return new AccountIdentification4Choice1();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification61 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification61 createBranchAndFinancialInstitutionIdentification61() {
        return new BranchAndFinancialInstitutionIdentification61();
    }

    /**
     * Create an instance of {@link CashAccount381 }
     * 
     */
    public CashAccount381 createCashAccount381() {
        return new CashAccount381();
    }

    /**
     * Create an instance of {@link CashAccountType2Choice }
     * 
     */
    public CashAccountType2Choice createCashAccountType2Choice() {
        return new CashAccountType2Choice();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice1 }
     * 
     */
    public CategoryPurpose1Choice1 createCategoryPurpose1Choice1() {
        return new CategoryPurpose1Choice1();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification21 }
     * 
     */
    public ClearingSystemMemberIdentification21 createClearingSystemMemberIdentification21() {
        return new ClearingSystemMemberIdentification21();
    }

    /**
     * Create an instance of {@link DateAndDateTime2Choice }
     * 
     */
    public DateAndDateTime2Choice createDateAndDateTime2Choice() {
        return new DateAndDateTime2Choice();
    }

    /**
     * Create an instance of {@link DatePeriod2 }
     * 
     */
    public DatePeriod2 createDatePeriod2() {
        return new DatePeriod2();
    }

    /**
     * Create an instance of {@link FIToFIPaymentStatusReportV10 }
     * 
     */
    public FIToFIPaymentStatusReportV10 createFIToFIPaymentStatusReportV10() {
        return new FIToFIPaymentStatusReportV10();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification181 }
     * 
     */
    public FinancialInstitutionIdentification181 createFinancialInstitutionIdentification181() {
        return new FinancialInstitutionIdentification181();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification11 }
     * 
     */
    public GenericAccountIdentification11 createGenericAccountIdentification11() {
        return new GenericAccountIdentification11();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification11 }
     * 
     */
    public GenericFinancialIdentification11 createGenericFinancialIdentification11() {
        return new GenericFinancialIdentification11();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification11 }
     * 
     */
    public GenericOrganisationIdentification11 createGenericOrganisationIdentification11() {
        return new GenericOrganisationIdentification11();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification11 }
     * 
     */
    public GenericPersonIdentification11 createGenericPersonIdentification11() {
        return new GenericPersonIdentification11();
    }

    /**
     * Create an instance of {@link GroupHeader911 }
     * 
     */
    public GroupHeader911 createGroupHeader911() {
        return new GroupHeader911();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice1 }
     * 
     */
    public LocalInstrument2Choice1 createLocalInstrument2Choice1() {
        return new LocalInstrument2Choice1();
    }

    /**
     * Create an instance of {@link OrganisationIdentification291 }
     * 
     */
    public OrganisationIdentification291 createOrganisationIdentification291() {
        return new OrganisationIdentification291();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link OriginalGroupHeader171 }
     * 
     */
    public OriginalGroupHeader171 createOriginalGroupHeader171() {
        return new OriginalGroupHeader171();
    }

    /**
     * Create an instance of {@link OriginalTransactionReference281 }
     * 
     */
    public OriginalTransactionReference281 createOriginalTransactionReference281() {
        return new OriginalTransactionReference281();
    }

    /**
     * Create an instance of {@link Party38Choice1 }
     * 
     */
    public Party38Choice1 createParty38Choice1() {
        return new Party38Choice1();
    }

    /**
     * Create an instance of {@link Party40Choice1 }
     * 
     */
    public Party40Choice1 createParty40Choice1() {
        return new Party40Choice1();
    }

    /**
     * Create an instance of {@link PartyIdentification1351 }
     * 
     */
    public PartyIdentification1351 createPartyIdentification1351() {
        return new PartyIdentification1351();
    }

    /**
     * Create an instance of {@link PaymentTransaction1101 }
     * 
     */
    public PaymentTransaction1101 createPaymentTransaction1101() {
        return new PaymentTransaction1101();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation271 }
     * 
     */
    public PaymentTypeInformation271 createPaymentTypeInformation271() {
        return new PaymentTypeInformation271();
    }

    /**
     * Create an instance of {@link PersonIdentification131 }
     * 
     */
    public PersonIdentification131 createPersonIdentification131() {
        return new PersonIdentification131();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link PostalAddress241 }
     * 
     */
    public PostalAddress241 createPostalAddress241() {
        return new PostalAddress241();
    }

    /**
     * Create an instance of {@link ProxyAccountIdentification1 }
     * 
     */
    public ProxyAccountIdentification1 createProxyAccountIdentification1() {
        return new ProxyAccountIdentification1();
    }

    /**
     * Create an instance of {@link ProxyAccountType1Choice }
     * 
     */
    public ProxyAccountType1Choice createProxyAccountType1Choice() {
        return new ProxyAccountType1Choice();
    }

    /**
     * Create an instance of {@link ReferredDocumentInformation71 }
     * 
     */
    public ReferredDocumentInformation71 createReferredDocumentInformation71() {
        return new ReferredDocumentInformation71();
    }

    /**
     * Create an instance of {@link ReferredDocumentType3Choice1 }
     * 
     */
    public ReferredDocumentType3Choice1 createReferredDocumentType3Choice1() {
        return new ReferredDocumentType3Choice1();
    }

    /**
     * Create an instance of {@link ReferredDocumentType41 }
     * 
     */
    public ReferredDocumentType41 createReferredDocumentType41() {
        return new ReferredDocumentType41();
    }

    /**
     * Create an instance of {@link RemittanceInformation161 }
     * 
     */
    public RemittanceInformation161 createRemittanceInformation161() {
        return new RemittanceInformation161();
    }

    /**
     * Create an instance of {@link ServiceLevel8Choice1 }
     * 
     */
    public ServiceLevel8Choice1 createServiceLevel8Choice1() {
        return new ServiceLevel8Choice1();
    }

    /**
     * Create an instance of {@link StatusReason6Choice1 }
     * 
     */
    public StatusReason6Choice1 createStatusReason6Choice1() {
        return new StatusReason6Choice1();
    }

    /**
     * Create an instance of {@link StatusReasonInformation121 }
     * 
     */
    public StatusReasonInformation121 createStatusReasonInformation121() {
        return new StatusReasonInformation121();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation161 }
     * 
     */
    public StructuredRemittanceInformation161 createStructuredRemittanceInformation161() {
        return new StructuredRemittanceInformation161();
    }

    /**
     * Create an instance of {@link TaxAmount2 }
     * 
     */
    public TaxAmount2 createTaxAmount2() {
        return new TaxAmount2();
    }

    /**
     * Create an instance of {@link TaxAuthorisation1 }
     * 
     */
    public TaxAuthorisation1 createTaxAuthorisation1() {
        return new TaxAuthorisation1();
    }

    /**
     * Create an instance of {@link TaxInformation7 }
     * 
     */
    public TaxInformation7 createTaxInformation7() {
        return new TaxInformation7();
    }

    /**
     * Create an instance of {@link TaxParty1 }
     * 
     */
    public TaxParty1 createTaxParty1() {
        return new TaxParty1();
    }

    /**
     * Create an instance of {@link TaxParty2 }
     * 
     */
    public TaxParty2 createTaxParty2() {
        return new TaxParty2();
    }

    /**
     * Create an instance of {@link TaxPeriod2 }
     * 
     */
    public TaxPeriod2 createTaxPeriod2() {
        return new TaxPeriod2();
    }

    /**
     * Create an instance of {@link TaxRecord2 }
     * 
     */
    public TaxRecord2 createTaxRecord2() {
        return new TaxRecord2();
    }

    /**
     * Create an instance of {@link TaxRecordDetails2 }
     * 
     */
    public TaxRecordDetails2 createTaxRecordDetails2() {
        return new TaxRecordDetails2();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:pacs.002.001.10", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
