//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 11:21:03 AM GST 
//


package com.bornfire.jaxb.camt_019_001_07;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Reports on business day information.
 * 
 * <p>Java class for BusinessDay8__1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessDay8__1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SysId" type="{urn:iso:std:iso:20022:tech:xsd:camt.019.001.07}SystemIdentification2Choice__1"/&gt;
 *         &lt;element name="BizDayOrErr" type="{urn:iso:std:iso:20022:tech:xsd:camt.019.001.07}BusinessDayReportOrError10Choice__1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessDay8__1", propOrder = {
    "sysId",
    "bizDayOrErr"
})
public class BusinessDay81 {

    @XmlElement(name = "SysId", required = true)
    protected SystemIdentification2Choice1 sysId;
    @XmlElement(name = "BizDayOrErr", required = true)
    protected BusinessDayReportOrError10Choice1 bizDayOrErr;

    /**
     * Gets the value of the sysId property.
     * 
     * @return
     *     possible object is
     *     {@link SystemIdentification2Choice1 }
     *     
     */
    public SystemIdentification2Choice1 getSysId() {
        return sysId;
    }

    /**
     * Sets the value of the sysId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemIdentification2Choice1 }
     *     
     */
    public void setSysId(SystemIdentification2Choice1 value) {
        this.sysId = value;
    }

    /**
     * Gets the value of the bizDayOrErr property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessDayReportOrError10Choice1 }
     *     
     */
    public BusinessDayReportOrError10Choice1 getBizDayOrErr() {
        return bizDayOrErr;
    }

    /**
     * Sets the value of the bizDayOrErr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessDayReportOrError10Choice1 }
     *     
     */
    public void setBizDayOrErr(BusinessDayReportOrError10Choice1 value) {
        this.bizDayOrErr = value;
    }

}
