//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 11:21:03 AM GST 
//


package com.bornfire.jaxb.camt_019_001_07;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Payment system operational information, such as opening, closure, session period or events, given per currency.
 * 
 * <p>Java class for BusinessDay9__1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessDay9__1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SysDt" type="{urn:iso:std:iso:20022:tech:xsd:camt.019.001.07}DateAndDateTime2Choice"/&gt;
 *         &lt;element name="SysInfPerCcy" type="{urn:iso:std:iso:20022:tech:xsd:camt.019.001.07}SystemAvailabilityAndEvents3__1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessDay9__1", propOrder = {
    "sysDt",
    "sysInfPerCcy"
})
public class BusinessDay91 {

    @XmlElement(name = "SysDt", required = true)
    protected DateAndDateTime2Choice sysDt;
    @XmlElement(name = "SysInfPerCcy", required = true)
    protected SystemAvailabilityAndEvents31 sysInfPerCcy;

    /**
     * Gets the value of the sysDt property.
     * 
     * @return
     *     possible object is
     *     {@link DateAndDateTime2Choice }
     *     
     */
    public DateAndDateTime2Choice getSysDt() {
        return sysDt;
    }

    /**
     * Sets the value of the sysDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAndDateTime2Choice }
     *     
     */
    public void setSysDt(DateAndDateTime2Choice value) {
        this.sysDt = value;
    }

    /**
     * Gets the value of the sysInfPerCcy property.
     * 
     * @return
     *     possible object is
     *     {@link SystemAvailabilityAndEvents31 }
     *     
     */
    public SystemAvailabilityAndEvents31 getSysInfPerCcy() {
        return sysInfPerCcy;
    }

    /**
     * Sets the value of the sysInfPerCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemAvailabilityAndEvents31 }
     *     
     */
    public void setSysInfPerCcy(SystemAvailabilityAndEvents31 value) {
        this.sysInfPerCcy = value;
    }

}
