//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.02 at 11:21:03 AM GST 
//


package com.bornfire.jaxb.camt_019_001_07;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bornfire.jaxb.camt_019_001_07 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:camt.019.001.07", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bornfire.jaxb.camt_019_001_07
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link BusinessDay81 }
     * 
     */
    public BusinessDay81 createBusinessDay81() {
        return new BusinessDay81();
    }

    /**
     * Create an instance of {@link BusinessDay91 }
     * 
     */
    public BusinessDay91 createBusinessDay91() {
        return new BusinessDay91();
    }

    /**
     * Create an instance of {@link BusinessDayReportOrError10Choice1 }
     * 
     */
    public BusinessDayReportOrError10Choice1 createBusinessDayReportOrError10Choice1() {
        return new BusinessDayReportOrError10Choice1();
    }

    /**
     * Create an instance of {@link BusinessDayReportOrError9Choice1 }
     * 
     */
    public BusinessDayReportOrError9Choice1 createBusinessDayReportOrError9Choice1() {
        return new BusinessDayReportOrError9Choice1();
    }

    /**
     * Create an instance of {@link DateAndDateTime2Choice }
     * 
     */
    public DateAndDateTime2Choice createDateAndDateTime2Choice() {
        return new DateAndDateTime2Choice();
    }

    /**
     * Create an instance of {@link GenericIdentification11 }
     * 
     */
    public GenericIdentification11 createGenericIdentification11() {
        return new GenericIdentification11();
    }

    /**
     * Create an instance of {@link MarketInfrastructureIdentification1Choice1 }
     * 
     */
    public MarketInfrastructureIdentification1Choice1 createMarketInfrastructureIdentification1Choice1() {
        return new MarketInfrastructureIdentification1Choice1();
    }

    /**
     * Create an instance of {@link MessageHeader71 }
     * 
     */
    public MessageHeader71 createMessageHeader71() {
        return new MessageHeader71();
    }

    /**
     * Create an instance of {@link OriginalBusinessQuery11 }
     * 
     */
    public OriginalBusinessQuery11 createOriginalBusinessQuery11() {
        return new OriginalBusinessQuery11();
    }

    /**
     * Create an instance of {@link ReturnBusinessDayInformationV07 }
     * 
     */
    public ReturnBusinessDayInformationV07 createReturnBusinessDayInformationV07() {
        return new ReturnBusinessDayInformationV07();
    }

    /**
     * Create an instance of {@link SystemAvailabilityAndEvents31 }
     * 
     */
    public SystemAvailabilityAndEvents31 createSystemAvailabilityAndEvents31() {
        return new SystemAvailabilityAndEvents31();
    }

    /**
     * Create an instance of {@link SystemEvent31 }
     * 
     */
    public SystemEvent31 createSystemEvent31() {
        return new SystemEvent31();
    }

    /**
     * Create an instance of {@link SystemEventType4Choice1 }
     * 
     */
    public SystemEventType4Choice1 createSystemEventType4Choice1() {
        return new SystemEventType4Choice1();
    }

    /**
     * Create an instance of {@link SystemIdentification2Choice1 }
     * 
     */
    public SystemIdentification2Choice1 createSystemIdentification2Choice1() {
        return new SystemIdentification2Choice1();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:camt.019.001.07", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
