//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 07:21:15 PM GST 
//


package com.bornfire.jaxb.camt_053_001_08;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bornfire.jaxb.camt_053_001_08 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:camt.053.001.08", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bornfire.jaxb.camt_053_001_08
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice1 }
     * 
     */
    public AccountIdentification4Choice1 createAccountIdentification4Choice1() {
        return new AccountIdentification4Choice1();
    }

    /**
     * Create an instance of {@link AccountStatement91 }
     * 
     */
    public AccountStatement91 createAccountStatement91() {
        return new AccountStatement91();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link AmountAndDirection35 }
     * 
     */
    public AmountAndDirection35 createAmountAndDirection35() {
        return new AmountAndDirection35();
    }

    /**
     * Create an instance of {@link BalanceSubType1Choice }
     * 
     */
    public BalanceSubType1Choice createBalanceSubType1Choice() {
        return new BalanceSubType1Choice();
    }

    /**
     * Create an instance of {@link BalanceType10Choice }
     * 
     */
    public BalanceType10Choice createBalanceType10Choice() {
        return new BalanceType10Choice();
    }

    /**
     * Create an instance of {@link BalanceType13 }
     * 
     */
    public BalanceType13 createBalanceType13() {
        return new BalanceType13();
    }

    /**
     * Create an instance of {@link BankToCustomerStatementV08 }
     * 
     */
    public BankToCustomerStatementV08 createBankToCustomerStatementV08() {
        return new BankToCustomerStatementV08();
    }

    /**
     * Create an instance of {@link BankTransactionCodeStructure41 }
     * 
     */
    public BankTransactionCodeStructure41 createBankTransactionCodeStructure41() {
        return new BankTransactionCodeStructure41();
    }

    /**
     * Create an instance of {@link BatchInformation21 }
     * 
     */
    public BatchInformation21 createBatchInformation21() {
        return new BatchInformation21();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification61 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification61 createBranchAndFinancialInstitutionIdentification61() {
        return new BranchAndFinancialInstitutionIdentification61();
    }

    /**
     * Create an instance of {@link CashAccount381 }
     * 
     */
    public CashAccount381 createCashAccount381() {
        return new CashAccount381();
    }

    /**
     * Create an instance of {@link CashAccount391 }
     * 
     */
    public CashAccount391 createCashAccount391() {
        return new CashAccount391();
    }

    /**
     * Create an instance of {@link CashAccountType2Choice }
     * 
     */
    public CashAccountType2Choice createCashAccountType2Choice() {
        return new CashAccountType2Choice();
    }

    /**
     * Create an instance of {@link CashBalance81 }
     * 
     */
    public CashBalance81 createCashBalance81() {
        return new CashBalance81();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification21 }
     * 
     */
    public ClearingSystemMemberIdentification21 createClearingSystemMemberIdentification21() {
        return new ClearingSystemMemberIdentification21();
    }

    /**
     * Create an instance of {@link CreditLine3 }
     * 
     */
    public CreditLine3 createCreditLine3() {
        return new CreditLine3();
    }

    /**
     * Create an instance of {@link CreditLineType1Choice }
     * 
     */
    public CreditLineType1Choice createCreditLineType1Choice() {
        return new CreditLineType1Choice();
    }

    /**
     * Create an instance of {@link DateAndDateTime2Choice }
     * 
     */
    public DateAndDateTime2Choice createDateAndDateTime2Choice() {
        return new DateAndDateTime2Choice();
    }

    /**
     * Create an instance of {@link DateTimePeriod1 }
     * 
     */
    public DateTimePeriod1 createDateTimePeriod1() {
        return new DateTimePeriod1();
    }

    /**
     * Create an instance of {@link EntryDetails91 }
     * 
     */
    public EntryDetails91 createEntryDetails91() {
        return new EntryDetails91();
    }

    /**
     * Create an instance of {@link EntryStatus1Choice }
     * 
     */
    public EntryStatus1Choice createEntryStatus1Choice() {
        return new EntryStatus1Choice();
    }

    /**
     * Create an instance of {@link EntryTransaction101 }
     * 
     */
    public EntryTransaction101 createEntryTransaction101() {
        return new EntryTransaction101();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification181 }
     * 
     */
    public FinancialInstitutionIdentification181 createFinancialInstitutionIdentification181() {
        return new FinancialInstitutionIdentification181();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification11 }
     * 
     */
    public GenericAccountIdentification11 createGenericAccountIdentification11() {
        return new GenericAccountIdentification11();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification11 }
     * 
     */
    public GenericFinancialIdentification11 createGenericFinancialIdentification11() {
        return new GenericFinancialIdentification11();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification11 }
     * 
     */
    public GenericOrganisationIdentification11 createGenericOrganisationIdentification11() {
        return new GenericOrganisationIdentification11();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification11 }
     * 
     */
    public GenericPersonIdentification11 createGenericPersonIdentification11() {
        return new GenericPersonIdentification11();
    }

    /**
     * Create an instance of {@link GroupHeader811 }
     * 
     */
    public GroupHeader811 createGroupHeader811() {
        return new GroupHeader811();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice }
     * 
     */
    public LocalInstrument2Choice createLocalInstrument2Choice() {
        return new LocalInstrument2Choice();
    }

    /**
     * Create an instance of {@link NumberAndSumOfTransactions11 }
     * 
     */
    public NumberAndSumOfTransactions11 createNumberAndSumOfTransactions11() {
        return new NumberAndSumOfTransactions11();
    }

    /**
     * Create an instance of {@link NumberAndSumOfTransactions41 }
     * 
     */
    public NumberAndSumOfTransactions41 createNumberAndSumOfTransactions41() {
        return new NumberAndSumOfTransactions41();
    }

    /**
     * Create an instance of {@link OrganisationIdentification291 }
     * 
     */
    public OrganisationIdentification291 createOrganisationIdentification291() {
        return new OrganisationIdentification291();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link OriginalBusinessQuery1 }
     * 
     */
    public OriginalBusinessQuery1 createOriginalBusinessQuery1() {
        return new OriginalBusinessQuery1();
    }

    /**
     * Create an instance of {@link Pagination1 }
     * 
     */
    public Pagination1 createPagination1() {
        return new Pagination1();
    }

    /**
     * Create an instance of {@link Party38Choice1 }
     * 
     */
    public Party38Choice1 createParty38Choice1() {
        return new Party38Choice1();
    }

    /**
     * Create an instance of {@link Party40Choice1 }
     * 
     */
    public Party40Choice1 createParty40Choice1() {
        return new Party40Choice1();
    }

    /**
     * Create an instance of {@link PartyIdentification1351 }
     * 
     */
    public PartyIdentification1351 createPartyIdentification1351() {
        return new PartyIdentification1351();
    }

    /**
     * Create an instance of {@link PersonIdentification131 }
     * 
     */
    public PersonIdentification131 createPersonIdentification131() {
        return new PersonIdentification131();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link PostalAddress241 }
     * 
     */
    public PostalAddress241 createPostalAddress241() {
        return new PostalAddress241();
    }

    /**
     * Create an instance of {@link ProprietaryBankTransactionCodeStructure11 }
     * 
     */
    public ProprietaryBankTransactionCodeStructure11 createProprietaryBankTransactionCodeStructure11() {
        return new ProprietaryBankTransactionCodeStructure11();
    }

    /**
     * Create an instance of {@link ProprietaryReference1 }
     * 
     */
    public ProprietaryReference1 createProprietaryReference1() {
        return new ProprietaryReference1();
    }

    /**
     * Create an instance of {@link ProxyAccountIdentification1 }
     * 
     */
    public ProxyAccountIdentification1 createProxyAccountIdentification1() {
        return new ProxyAccountIdentification1();
    }

    /**
     * Create an instance of {@link ProxyAccountType1Choice }
     * 
     */
    public ProxyAccountType1Choice createProxyAccountType1Choice() {
        return new ProxyAccountType1Choice();
    }

    /**
     * Create an instance of {@link Purpose2Choice }
     * 
     */
    public Purpose2Choice createPurpose2Choice() {
        return new Purpose2Choice();
    }

    /**
     * Create an instance of {@link ReferredDocumentInformation71 }
     * 
     */
    public ReferredDocumentInformation71 createReferredDocumentInformation71() {
        return new ReferredDocumentInformation71();
    }

    /**
     * Create an instance of {@link ReferredDocumentType3Choice1 }
     * 
     */
    public ReferredDocumentType3Choice1 createReferredDocumentType3Choice1() {
        return new ReferredDocumentType3Choice1();
    }

    /**
     * Create an instance of {@link ReferredDocumentType41 }
     * 
     */
    public ReferredDocumentType41 createReferredDocumentType41() {
        return new ReferredDocumentType41();
    }

    /**
     * Create an instance of {@link RemittanceInformation161 }
     * 
     */
    public RemittanceInformation161 createRemittanceInformation161() {
        return new RemittanceInformation161();
    }

    /**
     * Create an instance of {@link ReportEntry101 }
     * 
     */
    public ReportEntry101 createReportEntry101() {
        return new ReportEntry101();
    }

    /**
     * Create an instance of {@link SequenceRange1 }
     * 
     */
    public SequenceRange1 createSequenceRange1() {
        return new SequenceRange1();
    }

    /**
     * Create an instance of {@link SequenceRange1Choice }
     * 
     */
    public SequenceRange1Choice createSequenceRange1Choice() {
        return new SequenceRange1Choice();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation161 }
     * 
     */
    public StructuredRemittanceInformation161 createStructuredRemittanceInformation161() {
        return new StructuredRemittanceInformation161();
    }

    /**
     * Create an instance of {@link TotalTransactions61 }
     * 
     */
    public TotalTransactions61 createTotalTransactions61() {
        return new TotalTransactions61();
    }

    /**
     * Create an instance of {@link TransactionAgents51 }
     * 
     */
    public TransactionAgents51 createTransactionAgents51() {
        return new TransactionAgents51();
    }

    /**
     * Create an instance of {@link TransactionParties61 }
     * 
     */
    public TransactionParties61 createTransactionParties61() {
        return new TransactionParties61();
    }

    /**
     * Create an instance of {@link TransactionReferences61 }
     * 
     */
    public TransactionReferences61 createTransactionReferences61() {
        return new TransactionReferences61();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:camt.053.001.08", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
