//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 10:20:56 AM GST 
//


package com.bornfire.jaxb.camt_009_001_07;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The GetLimit message is used to request information on the details of one or more limits set by the member (or on behalf of the member) and managed by the transaction administrator.
 * 
 * <p>Java class for GetLimitV07 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetLimitV07"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MsgHdr" type="{urn:iso:std:iso:20022:tech:xsd:camt.009.001.07}MessageHeader9__1"/&gt;
 *         &lt;element name="LmtQryDef" type="{urn:iso:std:iso:20022:tech:xsd:camt.009.001.07}LimitQuery4__1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetLimitV07", propOrder = {
    "msgHdr",
    "lmtQryDef"
})
public class GetLimitV07 {

    @XmlElement(name = "MsgHdr", required = true)
    protected MessageHeader91 msgHdr;
    @XmlElement(name = "LmtQryDef", required = true)
    protected LimitQuery41 lmtQryDef;

    /**
     * Gets the value of the msgHdr property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeader91 }
     *     
     */
    public MessageHeader91 getMsgHdr() {
        return msgHdr;
    }

    /**
     * Sets the value of the msgHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeader91 }
     *     
     */
    public void setMsgHdr(MessageHeader91 value) {
        this.msgHdr = value;
    }

    /**
     * Gets the value of the lmtQryDef property.
     * 
     * @return
     *     possible object is
     *     {@link LimitQuery41 }
     *     
     */
    public LimitQuery41 getLmtQryDef() {
        return lmtQryDef;
    }

    /**
     * Sets the value of the lmtQryDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitQuery41 }
     *     
     */
    public void setLmtQryDef(LimitQuery41 value) {
        this.lmtQryDef = value;
    }

}
