//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 10:20:56 AM GST 
//


package com.bornfire.jaxb.camt_009_001_07;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the criteria used to search for a limit.
 * 
 * <p>Java class for LimitSearchCriteria6__1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LimitSearchCriteria6__1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SysId" type="{urn:iso:std:iso:20022:tech:xsd:camt.009.001.07}SystemIdentification2Choice__1" minOccurs="0"/&gt;
 *         &lt;element name="BilLmtCtrPtyId" type="{urn:iso:std:iso:20022:tech:xsd:camt.009.001.07}BranchAndFinancialInstitutionIdentification6__1" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CurLmtTp" type="{urn:iso:std:iso:20022:tech:xsd:camt.009.001.07}LimitType1Choice__1" minOccurs="0"/&gt;
 *         &lt;element name="AcctId" type="{urn:iso:std:iso:20022:tech:xsd:camt.009.001.07}AccountIdentification4Choice__1"/&gt;
 *         &lt;element name="LmtCcy" type="{urn:iso:std:iso:20022:tech:xsd:camt.009.001.07}ActiveCurrencyCode" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LimitSearchCriteria6__1", propOrder = {
    "sysId",
    "bilLmtCtrPtyId",
    "curLmtTp",
    "acctId",
    "lmtCcy"
})
public class LimitSearchCriteria61 {

    @XmlElement(name = "SysId")
    protected SystemIdentification2Choice1 sysId;
    @XmlElement(name = "BilLmtCtrPtyId")
    protected List<BranchAndFinancialInstitutionIdentification61> bilLmtCtrPtyId;
    @XmlElement(name = "CurLmtTp")
    protected LimitType1Choice1 curLmtTp;
    @XmlElement(name = "AcctId", required = true)
    protected AccountIdentification4Choice1 acctId;
    @XmlElement(name = "LmtCcy")
    protected String lmtCcy;

    /**
     * Gets the value of the sysId property.
     * 
     * @return
     *     possible object is
     *     {@link SystemIdentification2Choice1 }
     *     
     */
    public SystemIdentification2Choice1 getSysId() {
        return sysId;
    }

    /**
     * Sets the value of the sysId property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemIdentification2Choice1 }
     *     
     */
    public void setSysId(SystemIdentification2Choice1 value) {
        this.sysId = value;
    }

    /**
     * Gets the value of the bilLmtCtrPtyId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bilLmtCtrPtyId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBilLmtCtrPtyId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BranchAndFinancialInstitutionIdentification61 }
     * 
     * 
     */
    public List<BranchAndFinancialInstitutionIdentification61> getBilLmtCtrPtyId() {
        if (bilLmtCtrPtyId == null) {
            bilLmtCtrPtyId = new ArrayList<BranchAndFinancialInstitutionIdentification61>();
        }
        return this.bilLmtCtrPtyId;
    }

    /**
     * Gets the value of the curLmtTp property.
     * 
     * @return
     *     possible object is
     *     {@link LimitType1Choice1 }
     *     
     */
    public LimitType1Choice1 getCurLmtTp() {
        return curLmtTp;
    }

    /**
     * Sets the value of the curLmtTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitType1Choice1 }
     *     
     */
    public void setCurLmtTp(LimitType1Choice1 value) {
        this.curLmtTp = value;
    }

    /**
     * Gets the value of the acctId property.
     * 
     * @return
     *     possible object is
     *     {@link AccountIdentification4Choice1 }
     *     
     */
    public AccountIdentification4Choice1 getAcctId() {
        return acctId;
    }

    /**
     * Sets the value of the acctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountIdentification4Choice1 }
     *     
     */
    public void setAcctId(AccountIdentification4Choice1 value) {
        this.acctId = value;
    }

    /**
     * Gets the value of the lmtCcy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLmtCcy() {
        return lmtCcy;
    }

    /**
     * Sets the value of the lmtCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLmtCcy(String value) {
        this.lmtCcy = value;
    }

}
