//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 10:20:56 AM GST 
//


package com.bornfire.jaxb.camt_009_001_07;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the criteria to extract the limit information and the expected limit report. A name may be given to the new query.
 * 
 * <p>Java class for LimitCriteria6__1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LimitCriteria6__1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SchCrit" type="{urn:iso:std:iso:20022:tech:xsd:camt.009.001.07}LimitSearchCriteria6__1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LimitCriteria6__1", propOrder = {
    "schCrit"
})
public class LimitCriteria61 {

    @XmlElement(name = "SchCrit", required = true)
    protected LimitSearchCriteria61 schCrit;

    /**
     * Gets the value of the schCrit property.
     * 
     * @return
     *     possible object is
     *     {@link LimitSearchCriteria61 }
     *     
     */
    public LimitSearchCriteria61 getSchCrit() {
        return schCrit;
    }

    /**
     * Sets the value of the schCrit property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitSearchCriteria61 }
     *     
     */
    public void setSchCrit(LimitSearchCriteria61 value) {
        this.schCrit = value;
    }

}
