//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 10:20:56 AM GST 
//


package com.bornfire.jaxb.camt_009_001_07;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bornfire.jaxb.camt_009_001_07 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:camt.009.001.07", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bornfire.jaxb.camt_009_001_07
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice1 }
     * 
     */
    public AccountIdentification4Choice1 createAccountIdentification4Choice1() {
        return new AccountIdentification4Choice1();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification61 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification61 createBranchAndFinancialInstitutionIdentification61() {
        return new BranchAndFinancialInstitutionIdentification61();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification21 }
     * 
     */
    public ClearingSystemMemberIdentification21 createClearingSystemMemberIdentification21() {
        return new ClearingSystemMemberIdentification21();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification181 }
     * 
     */
    public FinancialInstitutionIdentification181 createFinancialInstitutionIdentification181() {
        return new FinancialInstitutionIdentification181();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification11 }
     * 
     */
    public GenericAccountIdentification11 createGenericAccountIdentification11() {
        return new GenericAccountIdentification11();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification11 }
     * 
     */
    public GenericFinancialIdentification11 createGenericFinancialIdentification11() {
        return new GenericFinancialIdentification11();
    }

    /**
     * Create an instance of {@link GetLimitV07 }
     * 
     */
    public GetLimitV07 createGetLimitV07() {
        return new GetLimitV07();
    }

    /**
     * Create an instance of {@link LimitCriteria6Choice1 }
     * 
     */
    public LimitCriteria6Choice1 createLimitCriteria6Choice1() {
        return new LimitCriteria6Choice1();
    }

    /**
     * Create an instance of {@link LimitCriteria61 }
     * 
     */
    public LimitCriteria61 createLimitCriteria61() {
        return new LimitCriteria61();
    }

    /**
     * Create an instance of {@link LimitQuery41 }
     * 
     */
    public LimitQuery41 createLimitQuery41() {
        return new LimitQuery41();
    }

    /**
     * Create an instance of {@link LimitSearchCriteria61 }
     * 
     */
    public LimitSearchCriteria61 createLimitSearchCriteria61() {
        return new LimitSearchCriteria61();
    }

    /**
     * Create an instance of {@link LimitType1Choice1 }
     * 
     */
    public LimitType1Choice1 createLimitType1Choice1() {
        return new LimitType1Choice1();
    }

    /**
     * Create an instance of {@link MarketInfrastructureIdentification1Choice1 }
     * 
     */
    public MarketInfrastructureIdentification1Choice1 createMarketInfrastructureIdentification1Choice1() {
        return new MarketInfrastructureIdentification1Choice1();
    }

    /**
     * Create an instance of {@link MessageHeader91 }
     * 
     */
    public MessageHeader91 createMessageHeader91() {
        return new MessageHeader91();
    }

    /**
     * Create an instance of {@link SystemIdentification2Choice1 }
     * 
     */
    public SystemIdentification2Choice1 createSystemIdentification2Choice1() {
        return new SystemIdentification2Choice1();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:camt.009.001.07", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
