//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 01:50:40 PM IST 
//


package com.bornfire.jaxb.block4;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Revision" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Header"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Message"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="SenderReference" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *                             &lt;element name="MessageIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="Sender"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="BIC12" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Receiver"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="BIC12" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Body"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{urn:swift:xsd:camt.998.001.03}Document"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "revision",
    "header",
    "body"
})
@XmlRootElement(name = "DataPDU", namespace = "urn:swift:saa:xsd:saa.2.0")
public class DataPDU {

    @XmlElement(name = "Revision", namespace = "urn:swift:saa:xsd:saa.2.0", required = true)
    protected String revision;
    @XmlElement(name = "Header", namespace = "urn:swift:saa:xsd:saa.2.0", required = true)
    protected DataPDU.Header header;
    @XmlElement(name = "Body", namespace = "urn:swift:saa:xsd:saa.2.0", required = true)
    protected DataPDU.Body body;

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevision(String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link DataPDU.Header }
     *     
     */
    public DataPDU.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataPDU.Header }
     *     
     */
    public void setHeader(DataPDU.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link DataPDU.Body }
     *     
     */
    public DataPDU.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataPDU.Body }
     *     
     */
    public void setBody(DataPDU.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{urn:swift:xsd:camt.998.001.03}Document"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "document"
    })
    public static class Body {
    	
    	@XmlElement(name = "Document", required = true)
    	protected BusinessApplicationHeader11 appHeader;

        @XmlElement(name = "Document", required = true)
        protected Object document;

        /**
         * Gets the value of the document property.
         * 
         * @return
         *     possible object is
         *     {@link Document }
         *     
         */
        public Object getDocument() {
            return document;
        }

        /**
         * Sets the value of the document property.
         * 
         * @param value
         *     allowed object is
         *     {@link Document }
         *     
         */
        public void setDocument(Object value) {
            this.document = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Message"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="SenderReference" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
     *                   &lt;element name="MessageIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="Sender"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="BIC12" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Receiver"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="BIC12" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "message"
    })
    public static class Header {

        @XmlElement(name = "Message", namespace = "urn:swift:saa:xsd:saa.2.0", required = true)
        protected DataPDU.Header.Message message;

        /**
         * Gets the value of the message property.
         * 
         * @return
         *     possible object is
         *     {@link DataPDU.Header.Message }
         *     
         */
        public DataPDU.Header.Message getMessage() {
            return message;
        }

        /**
         * Sets the value of the message property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataPDU.Header.Message }
         *     
         */
        public void setMessage(DataPDU.Header.Message value) {
            this.message = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="SenderReference" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
         *         &lt;element name="MessageIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="Sender"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="BIC12" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Receiver"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="BIC12" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "senderReference",
            "messageIdentifier",
            "format",
            "sender",
            "receiver"
        })
        public static class Message {

            @XmlElement(name = "SenderReference", namespace = "urn:swift:saa:xsd:saa.2.0", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger senderReference;
            @XmlElement(name = "MessageIdentifier", namespace = "urn:swift:saa:xsd:saa.2.0", required = true)
            protected String messageIdentifier;
            @XmlElement(name = "Format", namespace = "urn:swift:saa:xsd:saa.2.0", required = true)
            protected String format;
            @XmlElement(name = "Sender", namespace = "urn:swift:saa:xsd:saa.2.0", required = true)
            protected DataPDU.Header.Message.Sender sender;
            @XmlElement(name = "Receiver", namespace = "urn:swift:saa:xsd:saa.2.0", required = true)
            protected DataPDU.Header.Message.Receiver receiver;

            /**
             * Gets the value of the senderReference property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getSenderReference() {
                return senderReference;
            }

            /**
             * Sets the value of the senderReference property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setSenderReference(BigInteger value) {
                this.senderReference = value;
            }

            /**
             * Gets the value of the messageIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMessageIdentifier() {
                return messageIdentifier;
            }

            /**
             * Sets the value of the messageIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMessageIdentifier(String value) {
                this.messageIdentifier = value;
            }

            /**
             * Gets the value of the format property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFormat() {
                return format;
            }

            /**
             * Sets the value of the format property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFormat(String value) {
                this.format = value;
            }

            /**
             * Gets the value of the sender property.
             * 
             * @return
             *     possible object is
             *     {@link DataPDU.Header.Message.Sender }
             *     
             */
            public DataPDU.Header.Message.Sender getSender() {
                return sender;
            }

            /**
             * Sets the value of the sender property.
             * 
             * @param value
             *     allowed object is
             *     {@link DataPDU.Header.Message.Sender }
             *     
             */
            public void setSender(DataPDU.Header.Message.Sender value) {
                this.sender = value;
            }

            /**
             * Gets the value of the receiver property.
             * 
             * @return
             *     possible object is
             *     {@link DataPDU.Header.Message.Receiver }
             *     
             */
            public DataPDU.Header.Message.Receiver getReceiver() {
                return receiver;
            }

            /**
             * Sets the value of the receiver property.
             * 
             * @param value
             *     allowed object is
             *     {@link DataPDU.Header.Message.Receiver }
             *     
             */
            public void setReceiver(DataPDU.Header.Message.Receiver value) {
                this.receiver = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="BIC12" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "bic12"
            })
            public static class Receiver {

                @XmlElement(name = "BIC12", namespace = "urn:swift:saa:xsd:saa.2.0", required = true)
                protected String bic12;

                /**
                 * Gets the value of the bic12 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBIC12() {
                    return bic12;
                }

                /**
                 * Sets the value of the bic12 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBIC12(String value) {
                    this.bic12 = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="BIC12" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "bic12"
            })
            public static class Sender {

                @XmlElement(name = "BIC12", namespace = "urn:swift:saa:xsd:saa.2.0", required = true)
                protected String bic12;

                /**
                 * Gets the value of the bic12 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBIC12() {
                    return bic12;
                }

                /**
                 * Sets the value of the bic12 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBIC12(String value) {
                    this.bic12 = value;
                }

            }

        }

    }

}
