//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 10:25:48 AM GST 
//


package com.bornfire.jaxb.camt_011_001_07;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bornfire.jaxb.camt_011_001_07 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:camt.011.001.07", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bornfire.jaxb.camt_011_001_07
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice1 }
     * 
     */
    public AccountIdentification4Choice1 createAccountIdentification4Choice1() {
        return new AccountIdentification4Choice1();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAndAmount }
     * 
     */
    public ActiveCurrencyAndAmount createActiveCurrencyAndAmount() {
        return new ActiveCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link Amount2Choice1 }
     * 
     */
    public Amount2Choice1 createAmount2Choice1() {
        return new Amount2Choice1();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification61 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification61 createBranchAndFinancialInstitutionIdentification61() {
        return new BranchAndFinancialInstitutionIdentification61();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification21 }
     * 
     */
    public ClearingSystemMemberIdentification21 createClearingSystemMemberIdentification21() {
        return new ClearingSystemMemberIdentification21();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification181 }
     * 
     */
    public FinancialInstitutionIdentification181 createFinancialInstitutionIdentification181() {
        return new FinancialInstitutionIdentification181();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification11 }
     * 
     */
    public GenericAccountIdentification11 createGenericAccountIdentification11() {
        return new GenericAccountIdentification11();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification11 }
     * 
     */
    public GenericFinancialIdentification11 createGenericFinancialIdentification11() {
        return new GenericFinancialIdentification11();
    }

    /**
     * Create an instance of {@link Limit81 }
     * 
     */
    public Limit81 createLimit81() {
        return new Limit81();
    }

    /**
     * Create an instance of {@link LimitIdentification2Choice1 }
     * 
     */
    public LimitIdentification2Choice1 createLimitIdentification2Choice1() {
        return new LimitIdentification2Choice1();
    }

    /**
     * Create an instance of {@link LimitIdentification51 }
     * 
     */
    public LimitIdentification51 createLimitIdentification51() {
        return new LimitIdentification51();
    }

    /**
     * Create an instance of {@link LimitStructure31 }
     * 
     */
    public LimitStructure31 createLimitStructure31() {
        return new LimitStructure31();
    }

    /**
     * Create an instance of {@link LimitType1Choice1 }
     * 
     */
    public LimitType1Choice1 createLimitType1Choice1() {
        return new LimitType1Choice1();
    }

    /**
     * Create an instance of {@link MarketInfrastructureIdentification1Choice1 }
     * 
     */
    public MarketInfrastructureIdentification1Choice1 createMarketInfrastructureIdentification1Choice1() {
        return new MarketInfrastructureIdentification1Choice1();
    }

    /**
     * Create an instance of {@link MessageHeader11 }
     * 
     */
    public MessageHeader11 createMessageHeader11() {
        return new MessageHeader11();
    }

    /**
     * Create an instance of {@link ModifyLimitV07 }
     * 
     */
    public ModifyLimitV07 createModifyLimitV07() {
        return new ModifyLimitV07();
    }

    /**
     * Create an instance of {@link SystemIdentification2Choice1 }
     * 
     */
    public SystemIdentification2Choice1 createSystemIdentification2Choice1() {
        return new SystemIdentification2Choice1();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:camt.011.001.07", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
