//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 06:47:50 PM GST 
//


package com.bornfire.jaxb.camt_010_001_08;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Choice between risk management limit details or a business error when the requested data cannot be retrieved.
 * 
 * <p>Java class for LimitOrError4Choice__1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LimitOrError4Choice__1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Lmt" type="{urn:swift:xsd:camt.010.001.08}Limit7__1"/&gt;
 *           &lt;element name="BizErr" type="{urn:swift:xsd:camt.010.001.08}ErrorHandling5"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LimitOrError4Choice__1", propOrder = {
    "lmt",
    "bizErr"
})
public class LimitOrError4Choice1 {

    @XmlElement(name = "Lmt")
    protected Limit71 lmt;
    @XmlElement(name = "BizErr")
    protected ErrorHandling5 bizErr;

    /**
     * Gets the value of the lmt property.
     * 
     * @return
     *     possible object is
     *     {@link Limit71 }
     *     
     */
    public Limit71 getLmt() {
        return lmt;
    }

    /**
     * Sets the value of the lmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Limit71 }
     *     
     */
    public void setLmt(Limit71 value) {
        this.lmt = value;
    }

    /**
     * Gets the value of the bizErr property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorHandling5 }
     *     
     */
    public ErrorHandling5 getBizErr() {
        return bizErr;
    }

    /**
     * Sets the value of the bizErr property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorHandling5 }
     *     
     */
    public void setBizErr(ErrorHandling5 value) {
        this.bizErr = value;
    }

}
