//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 06:47:50 PM GST 
//


package com.bornfire.jaxb.camt_010_001_08;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Details on the limits.
 * 
 * <p>Java class for Limit7__1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Limit7__1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Amt" type="{urn:swift:xsd:camt.010.001.08}Amount2Choice__1"/&gt;
 *         &lt;element name="CdtDbtInd" type="{urn:swift:xsd:camt.010.001.08}CreditDebitCode" minOccurs="0"/&gt;
 *         &lt;element name="UsdAmt" type="{urn:swift:xsd:camt.010.001.08}Amount2Choice__1" minOccurs="0"/&gt;
 *         &lt;element name="UsdPctg" type="{urn:swift:xsd:camt.010.001.08}PercentageRate" minOccurs="0"/&gt;
 *         &lt;element name="RmngAmt" type="{urn:swift:xsd:camt.010.001.08}Amount2Choice__1" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Limit7__1", propOrder = {
    "amt",
    "cdtDbtInd",
    "usdAmt",
    "usdPctg",
    "rmngAmt"
})
public class Limit71 {

    @XmlElement(name = "Amt", required = true)
    protected Amount2Choice1 amt;
    @XmlElement(name = "CdtDbtInd")
    @XmlSchemaType(name = "string")
    protected CreditDebitCode cdtDbtInd;
    @XmlElement(name = "UsdAmt")
    protected Amount2Choice1 usdAmt;
    @XmlElement(name = "UsdPctg")
    protected BigDecimal usdPctg;
    @XmlElement(name = "RmngAmt")
    protected Amount2Choice1 rmngAmt;

    /**
     * Gets the value of the amt property.
     * 
     * @return
     *     possible object is
     *     {@link Amount2Choice1 }
     *     
     */
    public Amount2Choice1 getAmt() {
        return amt;
    }

    /**
     * Sets the value of the amt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount2Choice1 }
     *     
     */
    public void setAmt(Amount2Choice1 value) {
        this.amt = value;
    }

    /**
     * Gets the value of the cdtDbtInd property.
     * 
     * @return
     *     possible object is
     *     {@link CreditDebitCode }
     *     
     */
    public CreditDebitCode getCdtDbtInd() {
        return cdtDbtInd;
    }

    /**
     * Sets the value of the cdtDbtInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditDebitCode }
     *     
     */
    public void setCdtDbtInd(CreditDebitCode value) {
        this.cdtDbtInd = value;
    }

    /**
     * Gets the value of the usdAmt property.
     * 
     * @return
     *     possible object is
     *     {@link Amount2Choice1 }
     *     
     */
    public Amount2Choice1 getUsdAmt() {
        return usdAmt;
    }

    /**
     * Sets the value of the usdAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount2Choice1 }
     *     
     */
    public void setUsdAmt(Amount2Choice1 value) {
        this.usdAmt = value;
    }

    /**
     * Gets the value of the usdPctg property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUsdPctg() {
        return usdPctg;
    }

    /**
     * Sets the value of the usdPctg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUsdPctg(BigDecimal value) {
        this.usdPctg = value;
    }

    /**
     * Gets the value of the rmngAmt property.
     * 
     * @return
     *     possible object is
     *     {@link Amount2Choice1 }
     *     
     */
    public Amount2Choice1 getRmngAmt() {
        return rmngAmt;
    }

    /**
     * Sets the value of the rmngAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount2Choice1 }
     *     
     */
    public void setRmngAmt(Amount2Choice1 value) {
        this.rmngAmt = value;
    }

}
