//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 06:47:50 PM GST 
//


package com.bornfire.jaxb.camt_010_001_08;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Reports either on the risk management limit or on a business error.
 * 
 * <p>Java class for LimitReport7__1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LimitReport7__1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LmtId" type="{urn:swift:xsd:camt.010.001.08}LimitIdentification5__1"/&gt;
 *         &lt;element name="LmtOrErr" type="{urn:swift:xsd:camt.010.001.08}LimitOrError4Choice__1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LimitReport7__1", propOrder = {
    "lmtId",
    "lmtOrErr"
})
public class LimitReport71 {

    @XmlElement(name = "LmtId", required = true)
    protected LimitIdentification51 lmtId;
    @XmlElement(name = "LmtOrErr", required = true)
    protected LimitOrError4Choice1 lmtOrErr;

    /**
     * Gets the value of the lmtId property.
     * 
     * @return
     *     possible object is
     *     {@link LimitIdentification51 }
     *     
     */
    public LimitIdentification51 getLmtId() {
        return lmtId;
    }

    /**
     * Sets the value of the lmtId property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitIdentification51 }
     *     
     */
    public void setLmtId(LimitIdentification51 value) {
        this.lmtId = value;
    }

    /**
     * Gets the value of the lmtOrErr property.
     * 
     * @return
     *     possible object is
     *     {@link LimitOrError4Choice1 }
     *     
     */
    public LimitOrError4Choice1 getLmtOrErr() {
        return lmtOrErr;
    }

    /**
     * Sets the value of the lmtOrErr property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitOrError4Choice1 }
     *     
     */
    public void setLmtOrErr(LimitOrError4Choice1 value) {
        this.lmtOrErr = value;
    }

}
