//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 06:47:50 PM GST 
//


package com.bornfire.jaxb.camt_010_001_08;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bornfire.jaxb.camt_010_001_08 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:swift:xsd:camt.010.001.08", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bornfire.jaxb.camt_010_001_08
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice1 }
     * 
     */
    public AccountIdentification4Choice1 createAccountIdentification4Choice1() {
        return new AccountIdentification4Choice1();
    }

    /**
     * Create an instance of {@link ActiveCurrencyAndAmount }
     * 
     */
    public ActiveCurrencyAndAmount createActiveCurrencyAndAmount() {
        return new ActiveCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link Amount2Choice1 }
     * 
     */
    public Amount2Choice1 createAmount2Choice1() {
        return new Amount2Choice1();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification61 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification61 createBranchAndFinancialInstitutionIdentification61() {
        return new BranchAndFinancialInstitutionIdentification61();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification21 }
     * 
     */
    public ClearingSystemMemberIdentification21 createClearingSystemMemberIdentification21() {
        return new ClearingSystemMemberIdentification21();
    }

    /**
     * Create an instance of {@link ErrorHandling3Choice }
     * 
     */
    public ErrorHandling3Choice createErrorHandling3Choice() {
        return new ErrorHandling3Choice();
    }

    /**
     * Create an instance of {@link ErrorHandling5 }
     * 
     */
    public ErrorHandling5 createErrorHandling5() {
        return new ErrorHandling5();
    }

    /**
     * Create an instance of {@link FinancialIdentificationSchemeName1Choice }
     * 
     */
    public FinancialIdentificationSchemeName1Choice createFinancialIdentificationSchemeName1Choice() {
        return new FinancialIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification181 }
     * 
     */
    public FinancialInstitutionIdentification181 createFinancialInstitutionIdentification181() {
        return new FinancialInstitutionIdentification181();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification11 }
     * 
     */
    public GenericAccountIdentification11 createGenericAccountIdentification11() {
        return new GenericAccountIdentification11();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification11 }
     * 
     */
    public GenericFinancialIdentification11 createGenericFinancialIdentification11() {
        return new GenericFinancialIdentification11();
    }

    /**
     * Create an instance of {@link Limit71 }
     * 
     */
    public Limit71 createLimit71() {
        return new Limit71();
    }

    /**
     * Create an instance of {@link LimitIdentification51 }
     * 
     */
    public LimitIdentification51 createLimitIdentification51() {
        return new LimitIdentification51();
    }

    /**
     * Create an instance of {@link LimitOrError4Choice1 }
     * 
     */
    public LimitOrError4Choice1 createLimitOrError4Choice1() {
        return new LimitOrError4Choice1();
    }

    /**
     * Create an instance of {@link LimitReport71 }
     * 
     */
    public LimitReport71 createLimitReport71() {
        return new LimitReport71();
    }

    /**
     * Create an instance of {@link LimitReportOrError4Choice1 }
     * 
     */
    public LimitReportOrError4Choice1 createLimitReportOrError4Choice1() {
        return new LimitReportOrError4Choice1();
    }

    /**
     * Create an instance of {@link LimitType1Choice1 }
     * 
     */
    public LimitType1Choice1 createLimitType1Choice1() {
        return new LimitType1Choice1();
    }

    /**
     * Create an instance of {@link Limits71 }
     * 
     */
    public Limits71 createLimits71() {
        return new Limits71();
    }

    /**
     * Create an instance of {@link MarketInfrastructureIdentification1Choice1 }
     * 
     */
    public MarketInfrastructureIdentification1Choice1 createMarketInfrastructureIdentification1Choice1() {
        return new MarketInfrastructureIdentification1Choice1();
    }

    /**
     * Create an instance of {@link MessageHeader71 }
     * 
     */
    public MessageHeader71 createMessageHeader71() {
        return new MessageHeader71();
    }

    /**
     * Create an instance of {@link OriginalBusinessQuery11 }
     * 
     */
    public OriginalBusinessQuery11 createOriginalBusinessQuery11() {
        return new OriginalBusinessQuery11();
    }

    /**
     * Create an instance of {@link ReturnLimitV08 }
     * 
     */
    public ReturnLimitV08 createReturnLimitV08() {
        return new ReturnLimitV08();
    }

    /**
     * Create an instance of {@link SystemIdentification2Choice1 }
     * 
     */
    public SystemIdentification2Choice1 createSystemIdentification2Choice1() {
        return new SystemIdentification2Choice1();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Document }{@code >}
     */
    @XmlElementDecl(namespace = "urn:swift:xsd:camt.010.001.08", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
