//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 06:47:50 PM GST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:swift:xsd:camt.010.001.08", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bornfire.jaxb.camt_010_001_08;
