//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 06:18:50 PM IST 
//


package com.bornfire.jaxb.pacs_008_001_08_dataPDU;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.bornfire.jaxb.head_001_001_01.BusinessApplicationHeader11;
import com.bornfire.jaxb.pacs_008_001_08.Document;
import com.bornfire.jaxb.pacs_008_001_08.GroupHeader931;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Body"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "body"
})
@XmlRootElement(name = "DataPDU")
public class DataPDU {

    @XmlElement(name = "Body", required = true)
    protected Body body;

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link DataPDU.Body }
     *     
     */
    public Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataPDU.Body }
     *     
     */
    public void setBody(Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)

    @XmlType(name = "body", propOrder = {
    	    "appHdr","document"
    	    
    	})
    public static class Body {

    	 @XmlElement(name = "AppHdr", required = true)
    	    protected BusinessApplicationHeader11 appHdr;
    	 @XmlElement(name = "Document", required = true)
 	    protected com.bornfire.jaxb.pacs_008_001_08.Document document;
    	 
		
		public BusinessApplicationHeader11 getAppHdr() {
			return appHdr;
		}

		public void setAppHdr(BusinessApplicationHeader11 appHdr) {
			this.appHdr = appHdr;
		}

		public com.bornfire.jaxb.pacs_008_001_08.Document getDocument() {
			return document;
		}

		public void setDocument(com.bornfire.jaxb.pacs_008_001_08.Document document) {
			this.document = document;
		}

		/*public Body(BusinessApplicationHeader11 appHdr, Document document) {
			super();
			this.appHdr = appHdr;
			this.document = document;
		}

		public Body() {
			super();
			// TODO Auto-generated constructor stub
		}
		*/
		
			 
    	 
    }

}
