//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.27 at 06:18:50 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:cma:stp:xsd:stp.1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bornfire.jaxb.pacs_008_001_08_dataPDU;
